# Server list generated by rankmirrors on 2016-09-24
#
# Arch Linux repository mirrorlist
# Generated on 2016-09-24
#

## China
Server = http://mirrors.cqu.edu.cn/archlinux/$repo/os/$arch
Server = http://mirror.lzu.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.neusoft.edu.cn/archlinux/$repo/os/$arch
Server = http://run.hit.edu.cn/archlinux/$repo/os/$arch
Server = https://mirrors.skyshe.cn/archlinux/$repo/os/$arch
Server = http://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch
Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.xjtu.edu.cn/archlinux/$repo/os/$arch
Server = https://mirrors.xjtu.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.zju.edu.cn/archlinux/$repo/os/$arch
Server = http://mirrors.163.com/archlinux/$repo/os/$arch

## - 北京理工大学
Server = http://mirror.bit.edu.cn/archlinux/

##- 阿里巴巴
Server = http://mirrors.aliyun.com/archlinux/

## - 上海交通大学y
Server = http://ftp.sjtu.edu.cn/archlinux/

## (ipv4 only)
Server = http://mirrors.4.tuna.tsinghua.edu.cn/archlinux/

## (ipv6 only)
Server = http://mirrors.6.tuna.tsinghua.edu.cn/archlinux/

## - 兰州大学
Server = http://mirror.lzu.edu.cn/archlinux/

##联通
Server = http://mirrors.sohu.com/archlinux/
Server = http://mirrors.yun-idc.com/archlinux/
